/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wiregram.gui.editors;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.DiagramObject;
import model.ListEventManager;

/**
 *
 * @author scyth
 */
public class DiagramObjectEditor extends javax.swing.JPanel implements ListSelectionListener, ListEventManager.ListListener<DiagramObject> {

    /**
     * Creates new form DiagramObjectEditor
     */
    public DiagramObjectEditor() {
        initComponents();
    }
    
    private DiagramObject primaryItem;
    public void setPrimaryItem(DiagramObject item) {        
        this.primaryItem = item;
        
        setVisible(this.primaryItem != null);
        
        DefaultListModel<DiagramObject> listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        
        if(item != null) {
            tfName.setText(item.getName());
            tfRefDes.setText(item.getRefDes());
            locationX.setValue(item.getX());
            locationY.setValue(item.getY());
            width.setValue(item.getWidth());
            height.setValue(item.getHeight());
            
            cbPrimaryItem.setSelectedItem(item);
            
            
            //listModel.addAll(primaryItem.getChildren());
            for(DiagramObject child : primaryItem.getChildren()) {
                listModel.addElement(child);
                for (DiagramObject grandchild : child.getChildren()) {
                    listModel.addElement(grandchild);
                }
            }
        } 
        
        
    }
    
    public DiagramObject getPrimaryItem() { return this.primaryItem; }
    public void pushChangesToPrimaryItem() {
        getPrimaryItem().setName(tfName.getText());
        getPrimaryItem().setRefDes(tfRefDes.getText());
        getPrimaryItem().setLocation((int)locationX.getValue(), (int)locationY.getValue());
        getPrimaryItem().setSize((int)width.getValue(), (int)height.getValue());
    }
    
    /**
     * Listens for changes in Diagram.SelectionManager's selected items list
     * @param selectedItems 
     */
    @Override
    public void listUpdated(ArrayList<DiagramObject> selectedItems) {
        
        DefaultComboBoxModel model = (DefaultComboBoxModel<DiagramObject>)cbPrimaryItem.getModel();
        model.removeAllElements();
        
        if(selectedItems == null || selectedItems.isEmpty()) 
            setPrimaryItem(null);
        else {
            model.addAll(selectedItems);
            setPrimaryItem(selectedItems.getFirst());
        }
    }
    
    @Override
    public void setEnabled(boolean enabled) {
        tfName.setEnabled(enabled);
        tfRefDes.setEnabled(enabled);
        locationX.setEnabled(enabled);
        locationY.setEnabled(enabled);
        width.setEnabled(enabled);
        height.setEnabled(enabled);
        
        cbPrimaryItem.setEnabled(enabled);
        
        super.setEnabled(enabled);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        JList source = (JList)e.getSource();
        setPrimaryItem((DiagramObject)source.getSelectedValue());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfRefDes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        locationX = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        locationY = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        width = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        height = new javax.swing.JSpinner();
        btnSave = new javax.swing.JButton();
        cbPrimaryItem = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Name: ");

        tfName.setText("jTextField1");
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tfRefDes.setText("jTextField1");
        tfRefDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("RefDes: ");

        jPanel1.setLayout(new java.awt.GridLayout(2, 4));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("X: ");
        jPanel1.add(jLabel3);
        jPanel1.add(locationX);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Y: ");
        jPanel1.add(jLabel5);
        jPanel1.add(locationY);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Width: ");
        jPanel1.add(jLabel4);
        jPanel1.add(width);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Height: ");
        jPanel1.add(jLabel6);
        jPanel1.add(height);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbPrimaryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrimaryItemActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRefDes, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tfName)))
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPrimaryItem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbPrimaryItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfRefDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        pushChangesToPrimaryItem();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbPrimaryItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrimaryItemActionPerformed
        setPrimaryItem((DiagramObject)cbPrimaryItem.getSelectedItem());
    }//GEN-LAST:event_cbPrimaryItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<DiagramObject> cbPrimaryItem;
    private javax.swing.JSpinner height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<DiagramObject> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner locationX;
    private javax.swing.JSpinner locationY;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfRefDes;
    private javax.swing.JSpinner width;
    // End of variables declaration//GEN-END:variables

}
