/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wiregram.gui;

import javax.swing.AbstractListModel;
import model.Component;
import model.Connector;
import model.Diagram;
import model.DiagramObject;
import model.Pin;

/**
 *
 * @author scyth
 */
public class DiagramEditor extends javax.swing.JPanel {

    private Diagram diagram = new Diagram();
    public void setDiagram(Diagram diagram){ this.diagram = diagram; }
    public final Diagram getDiagram() { return this.diagram; }
    
    /**
     * Creates new form DiagramPanel
     */
    public DiagramEditor() {
        initComponents();
        
        diagramPanel.setDiagram(getDiagram());
        
        initFakeData();
    }
    
    /**
     * Inserts example data for testing phase stuff
     */
    private void initFakeData() {
        Component BCCU = new Component(diagram, "28 BCCU", "2180B1");
        BCCU.setLocation(50, 150);
        BCCU.setHeight(200);
        BCCU.setWidth(100);
        diagram.add(BCCU);
        
        Component battery28 = new Component(diagram, "28 Batt", "2180B2");
        battery28.setLocation(BCCU.getRect().getRightBound() + 200, BCCU.getY());
        diagram.add(battery28);
        
        Component EDU1 = new Component(diagram, "EDU1", "2220B1");
        EDU1.setLocation(battery28.getX(), 0);
        diagram.add(EDU1);

        Component wow_switch = new Component(diagram, "WOW SWITCH", "32B15");
        wow_switch.setLocation(100, 50);
        diagram.add(wow_switch);
        
        Connector bccu_plug = new Connector(diagram, "J1/P1");
        bccu_plug.setRefDes("J1/P1");
        bccu_plug.setParentOffset(BCCU.getWidth(), 0);
        BCCU.addChild(bccu_plug);
        //bccu_plug.setParent(BCCU);
        //diagram.add(bccu_plug);
        
        bccu_plug.addChild(new Pin(diagram, "A"));
        bccu_plug.addChild(new Pin(diagram, "B"));
        bccu_plug.addChild(new Pin(diagram, "C"));
        bccu_plug.addChild(new Pin(diagram, "D"));
        bccu_plug.addChild(new Pin(diagram, "E"));
    }
    
    /**
     * Manages the List<DiagramObject> logic
     * @param <DiagramObject> 
     */
    private class DiagramListModel<DiagramObject> extends AbstractListModel<DiagramObject> {

        @Override
        public int getSize() {
            return getDiagram().getItems().size();
        }

        @Override
        public DiagramObject getElementAt(int index) {
            return (DiagramObject)getDiagram().getItems().get(index);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        componentsList = new javax.swing.JList<>();
        diagramPanel = new wiregram.gui.DiagramPanel();

        componentsList.setModel(new DiagramListModel());
        jScrollPane1.setViewportView(componentsList);

        javax.swing.GroupLayout diagramPanelLayout = new javax.swing.GroupLayout(diagramPanel);
        diagramPanel.setLayout(diagramPanelLayout);
        diagramPanelLayout.setHorizontalGroup(
            diagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        diagramPanelLayout.setVerticalGroup(
            diagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diagramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> componentsList;
    private wiregram.gui.DiagramPanel diagramPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
