/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wiregram.gui;

import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import model.Diagram;
import model.DiagramObject;
import model.SelectionManager;

/**
 *
 * @author scyth
 */
public class DiagramItemsList extends javax.swing.JPanel implements SelectionManager.SelectionListener {
    
    private Diagram diagram;
    public Diagram getDiagram() {
        return diagram;
    }
    public void setDiagram(Diagram diagram) {
        this.diagram = diagram;
    }
    
    /**
     * Creates new form DiagramItemsList
     */
    public DiagramItemsList() {
        initComponents();
    }
    
    @Override
    public void selectionUpdated(ArrayList<DiagramObject> selectedItems) {
        ArrayList<DiagramObject> items;
        if(!selectedItems.isEmpty())
            items = selectedItems;
        else
            items = getDiagram().getItems();
        
        itemsList.setModel(new DiagramListModel(items));
    }
    
    public void addListSelectionListener(ListSelectionListener l) { 
        itemsList.addListSelectionListener(l);
    }
    
    public void removeListSelectionListener(ListSelectionListener l) {
        itemsList.removeListSelectionListener(l);
    }
    
        /**
     * Manages the List<DiagramObject> logic
     * @param <DiagramObject> 
     */
    private class DiagramListModel<DiagramObject> extends AbstractListModel<DiagramObject> {

        private ArrayList<DiagramObject> items = new ArrayList<>();
        public ArrayList<DiagramObject> getItems() { return items; }
        
        public DiagramListModel(ArrayList<DiagramObject> list) {
            items = list;
        }
        
        @Override
        public int getSize() {
            return getItems().size();
        }

        @Override
        public DiagramObject getElementAt(int index) {
            return (DiagramObject)getItems().get(index);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        itemsList = new javax.swing.JList<>();
        itemsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        itemsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        itemsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(itemsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemsListValueChanged
        //evt.get
    }//GEN-LAST:event_itemsListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> itemsList;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
