/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wiregram.gui;

import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import model.Diagram;
import model.DiagramObject;
import model.ListEventManager;
import model.SelectionManager;

/**
 *
 * @author scyth
 */
public class DiagramItemsList extends javax.swing.JPanel implements Diagram.ItemsListener, ListEventManager.ListListener<DiagramObject> {
    
    private final DefaultListModel<DiagramObject> itemsListModel = new DefaultListModel<>();
    
    private Diagram diagram;
    public Diagram getDiagram() {
        return diagram;
    }
    public void setDiagram(Diagram diagram) {
        if(this.diagram != null) {
            this.diagram.getSelectionManager().removeListener(this);
            this.diagram.removeItemsListener(this);
        }
        
        this.diagram = diagram;
        
        if(this.diagram != null) {
            this.diagram.getSelectionManager().addListener(this);
            this.diagram.addItemsListener(this);
            itemsListModel.clear();
            itemsListModel.addAll(getDiagram().getItems());
            itemsList.setModel(itemsListModel);
        }
    }
    
    /**
     * Creates new form DiagramItemsList
     */
    public DiagramItemsList() {
        initComponents();
    }

    @Override
    public void itemAdded(DiagramObject item) {
        itemsListModel.addElement(item);
    }

    @Override
    public void itemRemoved(DiagramObject removed) {
        itemsListModel.removeElement(removed);
    }
    
    
    
    @Override
    public void listUpdated(ArrayList<DiagramObject> selectedItems) {
        
        if(pauseSelectionChangeEvents)
            return;
        
        int[] indices = new int[selectedItems.size()];
        
        for(int i = 0; i < selectedItems.size(); i++)
            indices[i] = (itemsListModel.indexOf(selectedItems.get(i)));
        
        itemsList.setSelectedIndices(indices);
    }
    
    public void addListSelectionListener(ListSelectionListener l) { 
        itemsList.addListSelectionListener(l);
    }
    
    public void removeListSelectionListener(ListSelectionListener l) {
        itemsList.removeListSelectionListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        itemsList = new javax.swing.JList<>();

        itemsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(itemsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the user selects or deselects DiagramObjects (items)
     * on the JList, this flag is used to prevent a feedback loop between here
     * and the diagram's selection events as we process selections and deselections
     */
    private boolean pauseSelectionChangeEvents = false;
    
    private void itemsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemsListValueChanged
        if(evt.getValueIsAdjusting() == false) {
            
            //avoid the feedback loop in diagram SelectionManager dishing out
            //events in response to selections & deselections
            pauseSelectionChangeEvents = true;
            
            var selectedItems = itemsList.getSelectedValuesList();
            for(DiagramObject item : getDiagram().getItems())
                if(!selectedItems.contains(item))
                    getDiagram().getSelectionManager().setSelected(item, false);
                else
                    getDiagram().setSelected(item, true);
            
            pauseSelectionChangeEvents = false;
        }
    }//GEN-LAST:event_itemsListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<DiagramObject> itemsList;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
