/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wiregram.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractListModel;
import model.Component;
import model.Connector;
import model.Diagram;
import model.DiagramObject;
import model.Pin;

/**
 *
 * @author scyth
 */
public class DiagramEditor extends javax.swing.JPanel {

    private Diagram diagram;
    public final void setDiagram(Diagram diagram){ 
        if(this.diagram != null)
            getDiagram().getSelectionManager().addListener(diagramObjectEditor1.DIAGRAM_SELECTION_LISTENER);
        
        this.diagram = diagram; 
        diagramPanel.setDiagram(getDiagram());
        diagramItemsList1.setDiagram(getDiagram());
        
        if(this.diagram != null)
            getDiagram().getSelectionManager().addListener(diagramObjectEditor1.DIAGRAM_SELECTION_LISTENER);
    }
    public final Diagram getDiagram() { return this.diagram; }
    
    /**
     * Creates new form DiagramPanel
     */
    public DiagramEditor() {
        initComponents();
        
        setDiagram(new Diagram());
        getDiagram().getSelectionManager().addListener(diagramItemsList1);
        
        diagramItemsList1.addListSelectionListener(diagramObjectEditor1.MASTER_LIST_SELECTION_CHANGE_LISTENER);
        
        initFakeData();
    }
    
    /**
     * Inserts example data for testing phase stuff
     */
    private void initFakeData() {
        Component BCCU = new Component("28 BCCU", "2180B1");
        BCCU.setLocation(50, 150);
        BCCU.setHeight(200);
        BCCU.setWidth(100);
        diagram.add(BCCU);
        
        Component battery28 = new Component("28 Batt", "2180B2");
        battery28.setLocation(BCCU.getRightBound() + 200, BCCU.getY());
        diagram.add(battery28);
        
        Component EDU1 = new Component("EDU1", "2220B1");
        EDU1.setLocation(battery28.getX(), 0);
        diagram.add(EDU1);

        Component wow_switch = new Component("WOW SWITCH", "32B15");
        wow_switch.setLocation(100, 50);
        diagram.add(wow_switch);
        
        Connector bccu_plug = new Connector("J1/P1");
        bccu_plug.setRefDes("J1/P1");
        bccu_plug.setParentOffset(BCCU.getWidth(), 0);
        BCCU.addChild(bccu_plug);
        //bccu_plug.setParent(BCCU);
        //diagram.add(bccu_plug);
        
        bccu_plug.addChild(new Pin("A"));
        bccu_plug.addChild(new Pin("B"));
        bccu_plug.addChild(new Pin("C"));
        bccu_plug.addChild(new Pin("D"));
        bccu_plug.addChild(new Pin("E"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        diagramObjectEditor1 = new wiregram.gui.editors.DiagramObjectEditor();
        diagramPanel = new wiregram.gui.DiagramPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAddComponent = new javax.swing.JButton();
        btnAddConnector = new javax.swing.JButton();
        diagramItemsList1 = new wiregram.gui.DiagramItemsList();

        setLayout(new java.awt.BorderLayout());

        diagramObjectEditor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diagramObjectEditor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(diagramObjectEditor1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.EAST);

        diagramPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout diagramPanelLayout = new javax.swing.GroupLayout(diagramPanel);
        diagramPanel.setLayout(diagramPanelLayout);
        diagramPanelLayout.setHorizontalGroup(
            diagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        diagramPanelLayout.setVerticalGroup(
            diagramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        add(diagramPanel, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnAddComponent.setText("Add Component");
        btnAddComponent.setFocusable(false);
        btnAddComponent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddComponent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddComponentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddComponent);

        btnAddConnector.setText("Add Connector");
        btnAddConnector.setFocusable(false);
        btnAddConnector.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddConnector.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddConnector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddConnectorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddConnector);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        diagramItemsList1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(diagramItemsList1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    //number used for "new_component_X" value
    private int newComponentIndex = 1;
    private void btnAddComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddComponentActionPerformed
        getDiagram().add(new Component("new_component" + newComponentIndex, "ref-des" + newComponentIndex++));
        repaint();
    }//GEN-LAST:event_btnAddComponentActionPerformed

    private void btnAddConnectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddConnectorActionPerformed
        DiagramObject primarySelectedItem = diagramObjectEditor1.getPrimaryItem();
        Connector connector = new Connector("new_component" + newComponentIndex++);
        
        primarySelectedItem.addChild(connector);
        connector.setParentOffset(primarySelectedItem.getWidth(), Component.CONNECTOR_SPACING);
        repaint();
    }//GEN-LAST:event_btnAddConnectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComponent;
    private javax.swing.JButton btnAddConnector;
    private wiregram.gui.DiagramItemsList diagramItemsList1;
    private wiregram.gui.editors.DiagramObjectEditor diagramObjectEditor1;
    private wiregram.gui.DiagramPanel diagramPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
